title: CubeGuelor
name: Guelor Emanuel
description: I am currently a Computer Science students studying at Carleton University in Ottawa aspiring to become professional software developer. The purpose of this site is to provide a place to publish my projects, and other related works. In my spare time I like to program, web/graphic design, painting, and creating concept art.

emailtest: gueloremanuel@cubeguelor.me
url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
